version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: devdb
    ports:
      - "27017:27017"

volumes:
  mongodb-data: